In [44]:
import numpy as np
import pandas as pd
from pandas_datareader import data, wb
import datetime
from dateutil.relativedelta import relativedelta
import matplotlib.pyplot as plt
from pandas import datetime
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import warnings
import plotly.express as px

<ipython-input-44-4b2405318d66>:7: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  from pandas import datetime

In [29]:
to_date=datetime.now()
start_date = to_date - relativedelta(years=5)
dates = pd.date_range(start_date, to_date)
df = data.DataReader('DELL', 'yahoo', dates[0],dates[-1],)
#df['Date']=df.index
#df.reset_index(inplace=True, drop=True)
df

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2016-08-17,24.363234,23.809525,24.086378,23.809525,137617.0,23.809525
2016-08-18,24.363234,23.532669,24.363234,23.671097,895776.0,23.671097
2016-08-19,24.086378,23.615725,23.643412,24.086378,2400355.0,24.086378
2016-08-22,25.249168,23.588039,23.809525,24.169436,1138322.0,24.169436
2016-08-23,25.415281,24.086378,24.224806,24.916945,751657.0,24.916945
...,...,...,...,...,...,...
2021-05-20,99.089996,97.050003,97.099998,98.610001,1420200.0,98.610001
2021-05-21,99.699997,98.309998,99.430000,98.470001,1164100.0,98.470001
2021-05-24,100.660004,99.139999,99.309998,100.139999,1853200.0,100.139999
2021-05-25,100.940002,99.440002,100.699997,99.510002,2067300.0,99.510002
2021-05-26,100.449997,99.360001,99.650002,99.660004,1680800.0,99.660004

In [30]:
df1=df[['Close']]
df1

                 Close
Date
2016-08-17   23.809525
2016-08-18   23.671097
2016-08-19   24.086378
2016-08-22   24.169436
2016-08-23   24.916945
...                ...
2021-05-20   98.610001
2021-05-21   98.470001
2021-05-24  100.139999
2021-05-25   99.510002
2021-05-26   99.660004

[1202 rows x 1 columns]

In [31]:
forecast_out=7
df1['prediction']=df1[['Close']].shift(-forecast_out)
df1

<ipython-input-31-d469938a0bba>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['prediction']=df1[['Close']].shift(-forecast_out)

                 Close  prediction
Date
2016-08-17   23.809525   25.332226
2016-08-18   23.671097   25.636766
2016-08-19   24.086378   25.000000
2016-08-22   24.169436   24.739756
2016-08-23   24.916945   24.086378
...                ...         ...
2021-05-20   98.610001         NaN
2021-05-21   98.470001         NaN
2021-05-24  100.139999         NaN
2021-05-25   99.510002         NaN
2021-05-26   99.660004         NaN

[1202 rows x 2 columns]

In [32]:
X=np.array(df1.drop(['prediction'],1))
X=X[:-forecast_out]
X

array([[23.80952454],
       [23.6710968 ],
       [24.0863781 ],
       ...,
       [96.40000153],
       [98.43000031],
       [98.38999939]])

In [33]:
Y=np.array(df1['prediction'])
Y=Y[:-forecast_out]
Y

array([ 25.3322258 ,  25.63676643,  25.        , ..., 100.13999939,
        99.51000214,  99.66000366])

In [34]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3)

In [35]:
svr_rbf=SVR(kernel='rbf',C=1e3,gamma=0.1)
svr_rbf.fit(x_train,y_train)

SVR(C=1000.0, gamma=0.1)

In [36]:
svm_confidence=svr_rbf.score(x_test,y_test)
svm_confidence

0.9584514289699991

In [58]:
a=[]
b=[]
for i in range(len(y_test)):
    a.append(x_test[i][0])
    b.append(y_test[i])
#gr={'Actual':a,'Predicted':b}
#gr1=pd.DataFrame(gr)
#figure2 = px.line(gr1,template='simple_white')
#figure2.update_layout(xaxis_title="index",yaxis_title="Stock Price")
#figure2.update_xaxes(rangeslider_visible=True)
#figure2.show()
a

[41.395347595214844,
 44.99446487426758,
 28.8700008392334,
 53.30010986328125,
 47.709999084472656,
 74.06999969482422,
 31.959999084472656,
 57.290000915527344,
 42.97895812988281,
 55.970001220703125,
 31.035436630249023,
 66.1500015258789,
 46.937984466552734,
 57.5858268737793,
 36.88261413574219,
 42.22037887573242,
 52.44186019897461,
 40.177188873291016,
 40.919158935546875,
 51.0099983215332,
 33.665557861328125,
 50.369998931884766,
 39.81174087524414,
 50.380001068115234,
 71.52999877929688,
 72.7300033569336,
 56.63999938964844,
 44.45736312866211,
 30.016611099243164,
 52.77000045776367,
 30.43743133544922,
 40.39313507080078,
 39.72314453125,
 65.0,
 35.99114227294922,
 47.68000030517578,
 49.459999084472656,
 54.623477935791016,
 24.08637809753418,
 32.56367874145508,
 35.919158935546875,
 54.20000076293945,
 39.79999923706055,
 38.31672286987305,
 26.15725326538086,
 35.43743133544922,
 51.86600112915039,
 48.150001525878906,
 28.682170867919922,
 51.68000030517578,
 70.33000183105469,
 53.849998474121094,
 50.540000915527344,
 26.500553131103516,
 67.54000091552734,
 52.349998474121094,
 51.720001220703125,
 67.3499984741211,
 26.76079750061035,
 37.4473991394043,
 51.2015495300293,
 55.56999969482422,
 49.5,
 52.04872512817383,
 35.653377532958984,
 34.87264633178711,
 64.04000091552734,
 92.58000183105469,
 60.70000076293945,
 52.619049072265625,
 54.380001068115234,
 55.060001373291016,
 69.81999969482422,
 52.60797119140625,
 52.746402740478516,
 47.27574920654297,
 64.87999725341797,
 27.07087516784668,
 101.41999816894531,
 57.95127487182617,
 40.849998474121094,
 58.43300247192383,
 31.31999969482422,
 69.43000030517578,
 43.45515060424805,
 49.04999923706055,
 40.08305740356445,
 48.07862854003906,
 45.72536087036133,
 39.7397575378418,
 50.439998626708984,
 27.41971206665039,
 42.38999938964844,
 36.057586669921875,
 44.060001373291016,
 72.0999984741211,
 24.739755630493164,
 53.75,
 98.33000183105469,
 45.415283203125,
 34.72314453125,
 35.1550407409668,
 28.72646713256836,
 72.16000366210938,
 49.18000030517578,
 34.97785186767578,
 62.849998474121094,
 41.41749572753906,
 27.13178253173828,
 53.25027847290039,
 35.23255920410156,
 52.79999923706055,
 38.04540252685547,
 36.900001525878906,
 38.849998474121094,
 47.59689712524414,
 34.64008712768555,
 66.41000366210938,
 98.4000015258789,
 26.500553131103516,
 27.33665657043457,
 62.130001068115234,
 73.25,
 53.34000015258789,
 31.251384735107422,
 89.4800033569336,
 70.91000366210938,
 44.822811126708984,
 45.5370979309082,
 52.52491760253906,
 35.58693313598633,
 26.08527183532715,
 26.83831787109375,
 34.833885192871094,
 61.83000183105469,
 49.939998626708984,
 57.02657699584961,
 43.32225799560547,
 51.290000915527344,
 53.25,
 38.68770980834961,
 43.38999938964844,
 54.150001525878906,
 52.54999923706055,
 26.79401969909668,
 53.029998779296875,
 52.225914001464844,
 45.189998626708984,
 38.75,
 29.772979736328125,
 28.870431900024414,
 48.470001220703125,
 52.480621337890625,
 33.942413330078125,
 75.94000244140625,
 51.77000045776367,
 68.66000366210938,
 61.7599983215332,
 54.34000015258789,
 46.84939193725586,
 58.57696533203125,
 59.90999984741211,
 99.7699966430664,
 79.58999633789062,
 41.09634780883789,
 32.7400016784668,
 53.130001068115234,
 34.4629020690918,
 72.91999816894531,
 50.52000045776367,
 54.70000076293945,
 67.9000015258789,
 32.4307861328125,
 50.77000045776367,
 44.459999084472656,
 42.689998626708984,
 29.379844665527344,
 46.59000015258789,
 69.02999877929688,
 60.95000076293945,
 38.90999984741211,
 55.27000045776367,
 60.459999084472656,
 41.15171813964844,
 51.20000076293945,
 35.39313507080078,
 53.538204193115234,
 27.353267669677734,
 40.54999923706055,
 52.9678840637207,
 45.56999969482422,
 41.34000015258789,
 53.83000183105469,
 40.24363327026367,
 45.93000030517578,
 40.387596130371094,
 72.43000030517578,
 36.6445198059082,
 49.15835952758789,
 40.47065353393555,
 45.130001068115234,
 49.380001068115234,
 51.2292366027832,
 60.61000061035156,
 71.2300033569336,
 51.55038833618164,
 53.22999954223633,
 34.71760940551758,
 54.43000030517578,
 34.39645767211914,
 35.38206100463867,
 52.150001525878906,
 34.928016662597656,
 31.279069900512695,
 44.57364273071289,
 37.15946960449219,
 64.61000061035156,
 42.25,
 68.19000244140625,
 45.53156280517578,
 42.14839553833008,
 60.79999923706055,
 88.58999633789062,
 46.83277893066406,
 25.166112899780273,
 50.797340393066406,
 35.54817199707031,
 85.11000061035156,
 35.25470733642578,
 31.72203826904297,
 101.05999755859375,
 41.2292366027832,
 51.7386474609375,
 35.481727600097656,
 37.264671325683594,
 43.787376403808594,
 46.869998931884766,
 43.18383026123047,
 25.332225799560547,
 69.5,
 40.797340393066406,
 51.06999969482422,
 62.790000915527344,
 81.69000244140625,
 34.42414093017578,
 69.6500015258789,
 66.55999755859375,
 54.29125213623047,
 42.70210266113281,
 38.89811706542969,
 48.290000915527344,
 26.83831787109375,
 62.75,
 46.12403106689453,
 26.461793899536133,
 53.29999923706055,
 25.86932373046875,
 35.69767379760742,
 52.320045471191406,
 47.68000030517578,
 48.942413330078125,
 51.599998474121094,
 49.459999084472656,
 37.13732147216797,
 49.650001525878906,
 53.4939079284668,
 35.68659973144531,
 40.238094329833984,
 76.75,
 42.09000015258789,
 35.27685546875,
 68.13999938964844,
 53.68217086791992,
 35.935768127441406,
 35.54263687133789,
 39.74529266357422,
 39.619998931884766,
 60.63999938964844,
 48.676631927490234,
 25.143964767456055,
 52.11000061035156,
 47.400001525878906,
 53.22999954223633,
 50.34000015258789,
 40.459999084472656,
 41.56146240234375,
 31.428571701049805,
 57.68000030517578,
 26.101882934570312,
 50.90999984741211,
 57.7400016784668,
 70.37999725341797,
 42.02104187011719,
 35.84164047241211,
 36.7386474609375,
 51.84385299682617,
 52.52491760253906,
 61.45000076293945,
 89.30000305175781,
 27.17608070373535,
 50.779998779296875,
 26.99889373779297,
 35.76411819458008,
 40.84000015258789,
 79.68000030517578,
 72.8499984741211,
 26.240310668945312,
 41.6002197265625,
 101.41000366210938,
 53.88704299926758,
 53.4939079284668,
 52.02000045776367,
 55.34000015258789,
 35.45957946777344,
 58.477298736572266,
 51.06999969482422,
 57.22999954223633,
 48.97010040283203,
 48.99778366088867,
 41.029998779296875,
 35.96345520019531,
 65.54000091552734,
 34.058692932128906,
 42.82392120361328,
 45.599998474121094,
 29.036544799804688,
 46.44518280029297,
 53.41999816894531,
 40.27685546875,
 49.63999938964844,
 66.37000274658203,
 54.772979736328125,
 101.4800033569336,
 61.27000045776367,
 49.38999938964844,
 35.930233001708984,
 52.68000030517578,
 60.02000045776367,
 41.118492126464844,
 93.87999725341797,
 35.7862663269043,
 37.1705436706543,
 44.619998931884766,
 50.30453872680664,
 45.04429626464844,
 32.081947326660156,
 53.72999954223633,
 36.046512603759766,
 73.73999786376953,
 59.54999923706055,
 49.97999954223633,
 50.459999084472656,
 62.43000030517578,
 56.79999923706055,
 51.926910400390625,
 74.86000061035156,
 37.41971206665039,
 68.18000030517578,
 44.72314453125]

In [38]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [39]:
lr_confidence=lr.score(x_test,y_test)
lr_confidence

0.952681091036051

In [40]:
x_forecast=np.array(df1.drop(['prediction'],1))[-forecast_out:]
x_forecast

array([[ 98.15000153],
       [ 96.80000305],
       [ 98.61000061],
       [ 98.47000122],
       [100.13999939],
       [ 99.51000214],
       [ 99.66000366]])

In [41]:
lr_pre=lr.predict(x_forecast)
lr_pre

array([ 98.65636524,  97.3050637 ,  99.11680833,  98.97667381,
       100.64828391, 100.01767857, 100.16782488])

In [42]:
svr_rbf_pre=svr_rbf.predict(x_forecast)
svr_rbf_pre

array([ 99.17087469,  96.80186925,  99.9563841 ,  99.74735167,
        99.33957855, 100.22844878, 100.07609603])